# Generated by Django 4.2.7 on 2024-01-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_userdetail_password_alter_userdetail_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slotname', models.CharField(max_length=50)),
                ('TimeRange', models.TextField()),
                ('Booked', models.BooleanField(default=False)),
                ('Bookedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userdetail')),
            ],
        ),
    ]
