# Generated by Django 4.2.7 on 2024-01-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='TimeRange',
            new_name='Timerange',
        ),
    ]
