# Generated by Django 4.2.7 on 2024-01-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_timerange_slot_timerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='Bookedby',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='app1.userdetail'),
        ),
    ]
