# Generated by Django 4.2.7 on 2024-01-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_slot_bookedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='Bookedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userdetail'),
        ),
    ]
