# Generated by Django 4.2.7 on 2024-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_slot_bookedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='Bookedby',
            field=models.TextField(default='admin'),
        ),
    ]
