# Generated by Django 4.2.7 on 2024-01-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_slot_bookedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='Bookdate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='Bookedby',
            field=models.TextField(),
        ),
    ]
