# Generated by Django 4.2.7 on 2024-02-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_bookedslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedslot',
            name='Booked',
        ),
    ]
