# Generated by Django 4.2.7 on 2024-02-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_bookedslot_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedslot',
            old_name='Bookdate',
            new_name='Bookeddate',
        ),
    ]
