# Generated by Django 4.2.7 on 2024-03-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_slot_bookdate_remove_slot_booked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='')),
                ('Name', models.CharField(max_length=100)),
                ('Sports', models.CharField(max_length=50)),
                ('Summary', models.TextField()),
                ('Charge', models.IntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
