# Generated by Django 4.2.7 on 2024-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_coachinfos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachinfos',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
