# Generated by Django 4.2.7 on 2024-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_coachinfos_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoachImage', models.ImageField(upload_to='')),
                ('Coach', models.TextField()),
                ('Sports', models.TextField()),
                ('Bookdate', models.TextField()),
                ('Bookeddate', models.TextField()),
                ('Bookedby', models.TextField()),
            ],
        ),
    ]
