# Generated by Django 4.2.7 on 2024-03-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_bookedcoach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedcoach',
            name='CoachImage',
        ),
    ]
