# Generated by Django 4.2.7 on 2024-03-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_bookedcoach_coachimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcoach',
            name='Time',
            field=models.TextField(blank=True),
        ),
    ]
